version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-keycloak
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-keycloak} -d ${POSTGRES_DB:-keycloak}"]  # Usa defaults si no seteados
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    cpus: 1.0
    mem_limit: 1024m
    mem_reservation: 512m
    pids_limit: 200

  # ----------------------------------------------------------------
  # 3. KEYCLOAK (PhaseTwo)
  # ----------------------------------------------------------------
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:26.4.2
    container_name: keycloak-prod
    restart: always
    env_file:
      - .env
    # Este comando usa Bash puro para intentar abrir una conexión al puerto 8080.
    # Si conecta, devuelve éxito (exit 0). Si falla, da error (exit 1).

    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8080"
        
    # 3. EL TRUCO DEL COMMAND
    # Al quitar '--optimized', obligamos a Keycloak a leer las variables KC_..._ENABLED
    # y auto-configurarse al arrancar. Tardará unos segundos más en iniciar, pero funcionará.
    entrypoint: ["/bin/sh"]
    command: -c "exec /opt/keycloak/bin/kc.sh start --optimized --log-level=ERROR,FATAL"

    networks:
      - keycloak-network
      - proxiable
    cpus: 1.5
    mem_limit: 1536m
    mem_reservation: 768m
    pids_limit: 400

    
volumes:
  postgres_data:

networks:
  proxiable:
    external: true
    name: proxiable # Asegúrate de que este nombre coincida exactamente con tu red externa
  keycloak-network:
    driver: bridge
